apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: echolog
  name: echolog-test
spec:
  selector:
    matchLabels:
      app: echolog
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echolog
    spec:
      containers:
      - env:
        - name: SPEED
          value: "1"
        image: azman0101/echolog:latest
        imagePullPolicy: IfNotPresent
        name: echolog
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 7
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
